### PR TITLE
EXG-Visualizer 1.0 added

### PR DESCRIPTION
**Pull request by Jamm02**
Visualize all biopotential signals through webpage using ESP32 wifi AP.

### CODE REVIEW

**Comment by lorforlinux** [comment]
Hey @Jamm02, this PR is invalid.
I am not able to see any files for the new software examples. please make sure you have pushed everything successfully.
Also, please share more detail about the workings in the PR description and If possible add images too.

**Comment by ChinmayLonkar** [comment]
Hey @lorforlinux 
All of the code is working fine without any issue but Readme file needs to be changed slightly... 
The changes include -

- It should be mentioned that  ESP32  Wi-Fi must be connected to the viewing device and also about using Arduino serial monitor for obtaining the IP address.
- Esp32_Oscilloscope names of files in the Readme should be changed to EXG-Visualizer.
- In Step 8 link http://YOUR-ESP32-IP/oscilloscope.html should be changed to  http://YOUR-ESP32-IP/visualizer.html

Rest of all code it working flawlessly!
Good Job @Jamm02 !

These are some images which I took during testing...

The Website-
image

Arduino Serial Monitor-
image

ESP-IDF Terminal
image

**Comment by lorforlinux** [comment]
Thank you for the detailed review @ChinmayLonkar.
Hey @Jamm02, Please look into the issue and update the files asap!

**Comment by Jamm02** [comment]
I'll add a new PR with necessary changes, thank you.

**Pull request closed without merging**
